"""add provider and model to chat_messages

Revision ID: a65d1b73848f
Revises: 34b7584ac882
Create Date: 2026-08-23 23:11:14.462938

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a65d1b73848f'
down_revision: str | Sequence[str] | None = '34b7584ac882'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('provider', sa.String(length=30), nullable=True))
    op.add_column('chat_messages', sa.Column('model', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'model')
    op.drop_column('chat_messages', 'provider')
    # ### end Alembic commands ###
